version: '3.8'

services:
  nginx:
    container_name: parmple_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        NGINX_CONF: default.conf      # 개발 환경 설정 파일
        COPY_STATIC: "false"          # 정적 파일 서빙 활성화 ( 프론트 프로젝트 구조분리로 필요없음 )
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/main/resources/static:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - app-network

  app:
    container_name: parmple_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src  # 소스 코드 실시간 반영
    environment:
      SPRING_PROFILES_ACTIVE: ${LOCAL_SPRING_PROFILES_ACTIVE}
      SPRING_DEVTOOLS_RESTART: true # Hot reload
      DB_HOST: parmple_pgsql # PostgreSQL 컨테이너 이름
      DB_PORT: ${LOCAL_DB_PORT}
      DB_NAME: ${LOCAL_DB_NAME}
      DB_USER: ${LOCAL_DB_USER}
      DB_PASSWORD: ${LOCAL_DB_PASSWORD}
    networks:
      - app-network

  postgresql:
    container_name: parmple_pgsql
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    environment:
      POSTGRES_DB: ${LOCAL_DB_NAME}
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
    ports:
      - "${LOCAL_DB_PORT}:${LOCAL_DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: