version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        NGINX_CONF: default-prod.conf # 운영 환경 설정 파일
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${PRODUCTION_SPRING_PROFILES_ACTIVE}
      DB_HOST: my-rds-endpoint.amazonaws.com # RDS 엔드포인트
      DB_PORT: ${PRODUCTION_DB_PORT}
      DB_NAME: ${PRODUCTION_DB_NAME}
      DB_USER: ${PRODUCTION_DB_USER}
      DB_PASSWORD: ${PRODUCTION_DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network: